//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string pid { get; set; }
        public string name { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> imported { get; set; }
        public string Image { get; set; }
        public Nullable<int> price { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string slug { get; set; }
    }
}
